AllInJohn.CARD_LITTLE_BOY_BLUE = Isaac.GetCardIdByName("Little Boy Blue")
AllInJohn.CARD_HAT_TRICK = Isaac.GetCardIdByName("Hat Trick")
AllInJohn.CARD_COMEDIANS_MANIFESTO = Isaac.GetCardIdByName("Comedian's Manifesto")
AllInJohn.CARD_LEXICON = Isaac.GetCardIdByName("Lexicon")
AllInJohn.CARD_GNASHER = Isaac.GetCardIdByName("Gnasher")
AllInJohn.CARD_SILVIO = Isaac.GetCardIdByName("Silvio")
AllInJohn.CARD_EULENSPIEGEL = Isaac.GetCardIdByName("Eulenspiegel")
AllInJohn.CARD_COCONUT = Isaac.GetCardIdByName("Coconut")

AllInJohn.COLLECTIBLE_GUESS_THE_JEST = Isaac.GetItemIdByName("Guess the Jest!")

AllInJohn.SFX_BALANCE = Isaac.GetSoundIdByName("AIJ - Balance")
AllInJohn.SFX_CASH = Isaac.GetSoundIdByName("AIJ - Cash")
AllInJohn.SFX_FOIL = Isaac.GetSoundIdByName("AIJ - Foil")
AllInJohn.SFX_FORGE = Isaac.GetSoundIdByName("AIJ - Forge")
AllInJohn.SFX_JIMBO = Isaac.GetSoundIdByName("AIJ - Jimbo")
AllInJohn.SFX_JOKER = Isaac.GetSoundIdByName("AIJ - Joker")
AllInJohn.SFX_MULT = Isaac.GetSoundIdByName("AIJ - Mult")
AllInJohn.SFX_XMULT = Isaac.GetSoundIdByName("AIJ - XMult")
AllInJohn.SFX_POLYCHROME = Isaac.GetSoundIdByName("AIJ - Polychrome")

local sfx = AllInJohn.SFX
sfx:Preload(AllInJohn.SFX_BALANCE)
sfx:Preload(AllInJohn.SFX_CASH)
sfx:Preload(AllInJohn.SFX_FOIL)
sfx:Preload(AllInJohn.SFX_FORGE)
sfx:Preload(AllInJohn.SFX_JIMBO)
sfx:Preload(AllInJohn.SFX_JOKER)
sfx:Preload(AllInJohn.SFX_MULT)
sfx:Preload(AllInJohn.SFX_XMULT)
sfx:Preload(AllInJohn.SFX_POLYCHROME)